import Head from 'next/head';
import Script from 'next/script';

export default function Page() {
  return <>
    <Head>
      <title>Portfolio / Concepts | eCitizen Digital</title>
      <meta name="description" content={'Explore concept projects and capability showcases from eCitizen Digital. Concept work is clearly labelled and no fabricated client results are used.'} />
      <link rel="canonical" href="https://ecitizendigital.com/portfolio" />
    </Head>
    <div dangerouslySetInnerHTML={{__html: '<div class="progress"></div><a class="skip" href="#main">Skip to content</a><header><div class="container nav"><a class="brand" href="/"><img alt="eCitizen Digital" src="/assets/ecitizen-lockup-horizontal-reversed.png"/></a><nav aria-label="Primary" class="navlinks"><a class="" href="/">Home</a><a class="" href="/services">Services</a><a class="" href="/packages">Packages</a><a class="active" href="/portfolio">Portfolio</a><a class="" href="/process">Process</a><a class="" href="/blog">Insights</a><a class="" href="/about">About</a></nav><div class="navcta"><a class="btn btn-primary" href="/contact">Book a Consultation</a><button aria-label="Menu" class="menu" data-menu="">☰</button></div></div></header><main id="main"><section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Portfolio / Concepts</span><h1 style="font-size:clamp(50px,7vw,90px);line-height:.9;letter-spacing:-.06em;margin:12px 0">Show the thinking.<br/>Then show the evidence.</h1></div><p>Launch-stage work is clearly labelled. No fabricated client results, logos or testimonials are presented as proof.</p></div><div class="work-grid"><article class="glass work large reveal"><span class="eyebrow">Concept project</span><h3 style="margin-top:70px">Local SME Growth Campaign</h3><p>Concept system connecting positioning, social content, paid media and conversion for a local service business.</p><span class="tag">Growth system · Demo</span></article><article class="glass work reveal"><span class="eyebrow">Demo project</span><h3 style="margin-top:70px">Conversion-first Website</h3><p>Modular website concept built around trust, service discovery and lead generation.</p><span class="tag">Web · UX</span></article></div></div></section></main><footer><div class="container"><div class="footer-grid"><div class="footer-brand"><img alt="eCitizen Digital" src="/assets/ecitizen-lockup-horizontal-reversed.png"/><p>Digital Growth Partner for SMEs. Strategy, technology and creative execution built around business outcomes.</p><p style="color:#c8ced7;font-weight:700">We Grow Brands, You Grow Business.</p></div><div class="footer-col"><h4>Explore</h4><a href="/services">Services</a><a href="/packages">Packages</a><a href="/portfolio">Portfolio</a><a href="/process">Process</a></div><div class="footer-col"><h4>Learn</h4><a href="/blog">Insights</a><a href="/faq">FAQ</a><a href="/about">About</a></div><div class="footer-col"><h4>Start</h4><a href="/contact">Book a Consultation</a><a href="mailto:hi@ecitizen.digital">hi@ecitizen.digital</a><a href="/contact">Contact</a></div></div><div class="footer-bottom"><span>© <span data-year=""></span> eCitizen Digital.</span><span><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/cookie">Cookies</a> · <a href="/lead-data">Lead Data</a></span></div></div></footer><div class="toast"></div>'}} />
    <Script src="/config.js" strategy="beforeInteractive" />
    <Script src="/app.js" strategy="afterInteractive" />
  </>;
}
